/*
 * IncFile1.h
 *
 * Created: 23.07.2017 10:14:00
 *  Author: smart
 */ 


#ifndef EEPROMADDRESSES_H_
#define EEPROMADDRESSES_H_


#define EEPROM_ADDRESS_LIGHTS 1
#define EEPROM_ADDRESS_FAN 2
#define EEPROM_ADDRESS_VENT 3
#define EEPROM_ADDRESS_HEATER 4
#define EEPROM_ADDRESS_HUMIDIFIER 5
#define EEPROM_ADDRESS_MAINTAIN_TEMP_DAY_MIN 6
#define EEPROM_ADDRESS_MAINTAIN_TEMP_DAY_MAX 7
#define EEPROM_ADDRESS_MAINTAIN_TEMP_NIGHT_MIN 8
#define EEPROM_ADDRESS_MAINTAIN_TEMP_NIGHT_MAX 9
#define EEPROM_ADDRESS_MAINTAIN_HUMIDITY 10
#define EEPROM_ADDRESS_DELTA_TEMP 11
#define EEPROM_ADDRESS_AUTO_MODE 12
#define EEPROM_ADDRESS_TEMP_SENSOR 13
#define EEPROM_ADDRESS_CRITICAL_TEMP 14

//#define EEPROM_ADDRESS_VENTFAN 7
#define EEPROM_ADDRESS_COOLING_MODE 15

#define EEPROM_ADDRESS_NIGHT_START_H 16
#define EEPROM_ADDRESS_NIGHT_START_M 17
#define EEPROM_ADDRESS_NIGHT_DURATION_START 18
#define EEPROM_ADDRESS_NIGHT_DURATION_END 19
#define EEPROM_ADDRESS_NIGHT_DURATION_CURR 20 // uint16
#define EEPROM_ADDRESS_NIGHT_DURATION_DELTA 22
#define EEPROM_ADDRESS_NIGHT_MODE 23
#define EEPROM_ADDRESS_TEMP_IN 24
#define EEPROM_ADDRESS_TEMP_OUT 36

#define EEPROM_ADDRESS_HUMIDITY 48
#define EEPROM_ADDRESS_TEMP_IN_DHT 60

#define EEPROM_ADDRESS_GROW_START_DAY 71
#define EEPROM_ADDRESS_GROW_START_MONTH 72
#define EEPROM_ADDRESS_GROW_START_YEAR 73
#define EEPROM_ADDRESS_GROW_DURATION 74
#define EEPROM_ADDRESS_AP_NAME 75
#define EEPROM_ADDRESS_AP_PASSWORD 90

#define CMD_ADDRESS_CLOCK 0x91 // for wifi only

#define VENT_REL 2
#define HUMIDIFYER_REL 6
#define HEATER_REL 5

#endif /* INCFILE1_H_ */